from __future__ import annotations

from smart_unpacker.detection.defaults import (
    DEFAULT_MAGIC_SIGNATURES,
    DEFAULT_TAIL_MAGIC_SIGNATURES,
    DEFAULT_WEAK_MAGIC_SIGNATURES,
)

MAGICS = dict(DEFAULT_MAGIC_SIGNATURES)
WEAK_MAGICS = dict(DEFAULT_WEAK_MAGIC_SIGNATURES)
TAIL_MAGICS = dict(DEFAULT_TAIL_MAGIC_SIGNATURES)
